### ISSUE TITLE
Update the link to preprocessed profiles in README

### ISSUE THREAD

**Issue by lopaavol** [carpenterlab/2021_Haghighi_NatureMethods#12]
Hi!

The repository README instructs using following command to download the preprocessed profiles:
aws s3 sync \
  --no-sign-request \
  s3://cellpainting-gallery/cpg0003-rosetta/broad/workspace/preprocessed_data .

However, the path does not exist. The correct one seems to end with preprocessed_data_gallery

**Comment by shntnu** [comment]
Oops! Now fixed (we had to update something recently (2023-03-01) and the folder named got changed. Thanks for reporting!
